kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-delete-checker
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  kind: ClusterRole
  name: namespace-delete-checker
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: namespace-delete-checker
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: namespace-delete-checker
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - 'get'
  - nonResourceURLs:
      - '*'
    verbs:
      - 'get'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-delete-checker
  namespace: default