apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-04-15T08:20:08Z"
  labels:
    app: namespace-delete-checker
  name: namespace-delete-checker
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: namespace-delete-checker
  sessionAffinity: None
  type: ClusterIP