apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: namespace-delete-checker-webhook
webhooks:
  - name: ns-deletion-checker.ctripcloud.github.com
    clientConfig:
      service:
        name: namespace-delete-checker
        namespace: default
        path: "/namespace/delete-check"
      caBundle: { caBundle }
    rules:
      - operations:
          - DELETE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - namespaces
    failurePolicy: Fail